apiVersion: v1
kind: Service
metadata:
  name: random-number-api-service
  namespace: default
spec:
  selector:
    app: random-number-api-green #  random-number-api-blue Blue/Green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
